/*
	RSPArrayOfAccessorialRateOverride.h
	The implementation of properties and methods for the RSPArrayOfAccessorialRateOverride array.
	Generated by SudzC.com
*/
#import "RSPArrayOfAccessorialRateOverride.h"

#import "RSPAccessorialRateOverride.h"
@implementation RSPArrayOfAccessorialRateOverride

	+ (id) createWithNode: (CXMLNode*) node
	{
		return [[self alloc] initWithNode: node];
	}

	- (id) initWithNode: (CXMLNode*) node
	{
		if(self = [self init]) {
			for(CXMLElement* child in [node children])
			{
				RSPAccessorialRateOverride* value = [[RSPAccessorialRateOverride createWithNode: child] object];
				if(value != nil) {
					[self addObject: value];
				}
			}
		}
		return self;
	}
	
	+ (NSMutableString*) serialize: (NSArray*) array
	{
		NSMutableString* s = [NSMutableString string];
		for(id item in array) {
			[s appendString: [item serialize: @"AccessorialRateOverride"]];
		}
		return s;
	}
@end
