/*
	RSPArrayOfDecimal.h
	The interface definition of properties and methods for the RSPArrayOfDecimal array.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@interface RSPArrayOfDecimal : SoapArray
{
}

@end
