/*
	RSPArrayOfFreightPricingDetails.h
	The interface definition of properties and methods for the RSPArrayOfFreightPricingDetails array.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class RSPFreightPricingDetails;
@interface RSPArrayOfFreightPricingDetails : SoapArray
{
}

@end
