/*
	RSPArrayOfRateResponsePrivileged.h
	The interface definition of properties and methods for the RSPArrayOfRateResponsePrivileged array.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class RSPRateResponsePrivileged;
@interface RSPArrayOfRateResponsePrivileged : SoapArray
{
}

@end
