/*
	RSPArrayOfPricingAccessorial.h
	The interface definition of properties and methods for the RSPArrayOfPricingAccessorial array.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class RSPPricingAccessorial;
@interface RSPArrayOfPricingAccessorial : SoapArray
{
}

@end
