/*
	RSPArrayOfArrayOfDecimal.h
	The interface definition of properties and methods for the RSPArrayOfArrayOfDecimal array.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class RSPArrayOfDecimal;
@interface RSPArrayOfArrayOfDecimal : SoapArray
{
}

@end
