/*
	RSPAccessorial.h
	The interface definition of properties and methods for the RSPAccessorial object.
	Generated by SudzC.com
*/

#import "Soap.h"
	

@interface RSPAccessorial : SoapObject
{
	NSString* _accCode;
	
}
		
	@property (retain, nonatomic) NSString* accCode;

	+ (RSPAccessorial*) createWithNode: (CXMLNode*) node;
	- (id) initWithNode: (CXMLNode*) node;
	- (NSMutableString*) serialize;
	- (NSMutableString*) serialize: (NSString*) nodeName;
	- (NSMutableString*) serializeAttributes;
	- (NSMutableString*) serializeElements;

@end
