/*
	RSPArrayOfSupplement.h
	The implementation of properties and methods for the RSPArrayOfSupplement array.
	Generated by SudzC.com
*/
#import "RSPArrayOfSupplement.h"

#import "RSPSupplement.h"
@implementation RSPArrayOfSupplement

	+ (id) createWithNode: (CXMLNode*) node
	{
		return [[self alloc] initWithNode: node];
	}

	- (id) initWithNode: (CXMLNode*) node
	{
		if(self = [self init]) {
			for(CXMLElement* child in [node children])
			{
				RSPSupplement* value = [[RSPSupplement createWithNode: child] object];
				if(value != nil) {
					[self addObject: value];
				}
			}
		}
		return self;
	}
	
	+ (NSMutableString*) serialize: (NSArray*) array
	{
		NSMutableString* s = [NSMutableString string];
		for(id item in array) {
			[s appendString: [item serialize: @"Supplement"]];
		}
		return s;
	}
@end
