/*
	RSPArrayOfRateResponsePrivileged.h
	The implementation of properties and methods for the RSPArrayOfRateResponsePrivileged array.
	Generated by SudzC.com
*/
#import "RSPArrayOfRateResponsePrivileged.h"

#import "RSPRateResponsePrivileged.h"
@implementation RSPArrayOfRateResponsePrivileged

	+ (id) createWithNode: (CXMLNode*) node
	{
		return [[self alloc] initWithNode: node];
	}

	- (id) initWithNode: (CXMLNode*) node
	{
		if(self = [self init]) {
			for(CXMLElement* child in [node children])
			{
				RSPRateResponsePrivileged* value = [[RSPRateResponsePrivileged createWithNode: child] object];
				if(value != nil) {
					[self addObject: value];
				}
			}
		}
		return self;
	}
	
	+ (NSMutableString*) serialize: (NSArray*) array
	{
		NSMutableString* s = [NSMutableString string];
		for(id item in array) {
			[s appendString: [item serialize: @"RateResponsePrivileged"]];
		}
		return s;
	}
@end
