/*
	RSPArrayOfAccessorial.h
	The interface definition of properties and methods for the RSPArrayOfAccessorial array.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class RSPAccessorial;
@interface RSPArrayOfAccessorial : SoapArray
{
}

@end
