/*
	RSPArrayOfPalletPositions.h
	The interface definition of properties and methods for the RSPArrayOfPalletPositions array.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class RSPPalletPositions;
@interface RSPArrayOfPalletPositions : SoapArray
{
}

@end
