/*
	RSPArrayOfAccessorialRateOverride.h
	The interface definition of properties and methods for the RSPArrayOfAccessorialRateOverride array.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class RSPAccessorialRateOverride;
@interface RSPArrayOfAccessorialRateOverride : SoapArray
{
}

@end
