/*
	RSPArrayOfTerminalInfo.h
	The interface definition of properties and methods for the RSPArrayOfTerminalInfo array.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class RSPTerminalInfo;
@interface RSPArrayOfTerminalInfo : SoapArray
{
}

@end
