/*
	RSPArrayOfFreightPricingDetails.h
	The implementation of properties and methods for the RSPArrayOfFreightPricingDetails array.
	Generated by SudzC.com
*/
#import "RSPArrayOfFreightPricingDetails.h"

#import "RSPFreightPricingDetails.h"
@implementation RSPArrayOfFreightPricingDetails

	+ (id) createWithNode: (CXMLNode*) node
	{
		return [[self alloc] initWithNode: node];
	}

	- (id) initWithNode: (CXMLNode*) node
	{
		if(self = [self init]) {
			for(CXMLElement* child in [node children])
			{
				RSPFreightPricingDetails* value = [[RSPFreightPricingDetails createWithNode: child] object];
				if(value != nil) {
					[self addObject: value];
				}
			}
		}
		return self;
	}
	
	+ (NSMutableString*) serialize: (NSArray*) array
	{
		NSMutableString* s = [NSMutableString string];
		for(id item in array) {
			[s appendString: [item serialize: @"FreightPricingDetails"]];
		}
		return s;
	}
@end
