/*
	RSPAccessorialRateOverride.h
	The interface definition of properties and methods for the RSPAccessorialRateOverride object.
	Generated by SudzC.com
*/

#import "Soap.h"
	

@interface RSPAccessorialRateOverride : SoapObject
{
	NSString* _accROCode;
	NSString* _accRODescription;
	NSString* _accROCostRateQualifier;
	NSString* _accROChargeRateQualifier;
	NSDecimalNumber* _accROCost;
	NSDecimalNumber* _accROCharge;
	NSDecimalNumber* _accROMarkupValue;
	NSString* _accRONote;
	BOOL _accROApplyMarkup;
	BOOL _accROIsDollarMarkup;
	BOOL _accROIsPercentMarkup;
	
}
		
	@property (retain, nonatomic) NSString* accROCode;
	@property (retain, nonatomic) NSString* accRODescription;
	@property (retain, nonatomic) NSString* accROCostRateQualifier;
	@property (retain, nonatomic) NSString* accROChargeRateQualifier;
	@property (retain, nonatomic) NSDecimalNumber* accROCost;
	@property (retain, nonatomic) NSDecimalNumber* accROCharge;
	@property (retain, nonatomic) NSDecimalNumber* accROMarkupValue;
	@property (retain, nonatomic) NSString* accRONote;
	@property BOOL accROApplyMarkup;
	@property BOOL accROIsDollarMarkup;
	@property BOOL accROIsPercentMarkup;

	+ (RSPAccessorialRateOverride*) createWithNode: (CXMLNode*) node;
	- (id) initWithNode: (CXMLNode*) node;
	- (NSMutableString*) serialize;
	- (NSMutableString*) serialize: (NSString*) nodeName;
	- (NSMutableString*) serializeAttributes;
	- (NSMutableString*) serializeElements;

@end
