/*
	RSPArrayOfSupplement.h
	The interface definition of properties and methods for the RSPArrayOfSupplement array.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class RSPSupplement;
@interface RSPArrayOfSupplement : SoapArray
{
}

@end
