/*
	RSPArrayOfCwtPricingDetails.h
	The interface definition of properties and methods for the RSPArrayOfCwtPricingDetails array.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class RSPCwtPricingDetails;
@interface RSPArrayOfCwtPricingDetails : SoapArray
{
}

@end
