/*
	RSPArrayOfStopOff.h
	The interface definition of properties and methods for the RSPArrayOfStopOff array.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class RSPStopOff;
@interface RSPArrayOfStopOff : SoapArray
{
}

@end
