/*
	RSPArrayOfArrayOfDecimal.h
	The implementation of properties and methods for the RSPArrayOfArrayOfDecimal array.
	Generated by SudzC.com
*/
#import "RSPArrayOfArrayOfDecimal.h"

#import "RSPArrayOfDecimal.h"
@implementation RSPArrayOfArrayOfDecimal

	+ (id) createWithNode: (CXMLNode*) node
	{
		return [[self alloc] initWithNode: node];
	}

	- (id) initWithNode: (CXMLNode*) node
	{
		if(self = [self init]) {
			for(CXMLElement* child in [node children])
			{
				NSMutableArray* value = [[NSMutableArray createWithNode: child] object];
				[self addObject: value];
			}
		}
		return self;
	}
	
	+ (NSMutableString*) serialize: (NSArray*) array
	{
		NSMutableString* s = [NSMutableString string];
		for(id item in array) {
			[s appendString: [RSPArrayOfDecimal serialize: item]];
		}
		return s;
	}
@end
