/*
	RSPArrayOfRateAdvisement.h
	The interface definition of properties and methods for the RSPArrayOfRateAdvisement array.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class RSPRateAdvisement;
@interface RSPArrayOfRateAdvisement : SoapArray
{
}

@end
