/*
	RSPArrayOfCwtPricingDetails.h
	The implementation of properties and methods for the RSPArrayOfCwtPricingDetails array.
	Generated by SudzC.com
*/
#import "RSPArrayOfCwtPricingDetails.h"

#import "RSPCwtPricingDetails.h"
@implementation RSPArrayOfCwtPricingDetails

	+ (id) createWithNode: (CXMLNode*) node
	{
		return [[self alloc] initWithNode: node];
	}

	- (id) initWithNode: (CXMLNode*) node
	{
		if(self = [self init]) {
			for(CXMLElement* child in [node children])
			{
				RSPCwtPricingDetails* value = [[RSPCwtPricingDetails createWithNode: child] object];
				if(value != nil) {
					[self addObject: value];
				}
			}
		}
		return self;
	}
	
	+ (NSMutableString*) serialize: (NSArray*) array
	{
		NSMutableString* s = [NSMutableString string];
		for(id item in array) {
			[s appendString: [item serialize: @"CwtPricingDetails"]];
		}
		return s;
	}
@end
