/*
	RSPArrayOfStopOff.h
	The implementation of properties and methods for the RSPArrayOfStopOff array.
	Generated by SudzC.com
*/
#import "RSPArrayOfStopOff.h"

#import "RSPStopOff.h"
@implementation RSPArrayOfStopOff

	+ (id) createWithNode: (CXMLNode*) node
	{
		return [[self alloc] initWithNode: node];
	}

	- (id) initWithNode: (CXMLNode*) node
	{
		if(self = [self init]) {
			for(CXMLElement* child in [node children])
			{
				RSPStopOff* value = [[RSPStopOff createWithNode: child] object];
				if(value != nil) {
					[self addObject: value];
				}
			}
		}
		return self;
	}
	
	+ (NSMutableString*) serialize: (NSArray*) array
	{
		NSMutableString* s = [NSMutableString string];
		for(id item in array) {
			[s appendString: [item serialize: @"StopOff"]];
		}
		return s;
	}
@end
