/*
	RSPArrayOfRatedAccessorialPrivileged.h
	The interface definition of properties and methods for the RSPArrayOfRatedAccessorialPrivileged array.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class RSPRatedAccessorialPrivileged;
@interface RSPArrayOfRatedAccessorialPrivileged : SoapArray
{
}

@end
