/*
	RSPArrayOfRateAdvisement.h
	The implementation of properties and methods for the RSPArrayOfRateAdvisement array.
	Generated by SudzC.com
*/
#import "RSPArrayOfRateAdvisement.h"

#import "RSPRateAdvisement.h"
@implementation RSPArrayOfRateAdvisement

	+ (id) createWithNode: (CXMLNode*) node
	{
		return [[self alloc] initWithNode: node];
	}

	- (id) initWithNode: (CXMLNode*) node
	{
		if(self = [self init]) {
			for(CXMLElement* child in [node children])
			{
				RSPRateAdvisement* value = [[RSPRateAdvisement createWithNode: child] object];
				if(value != nil) {
					[self addObject: value];
				}
			}
		}
		return self;
	}
	
	+ (NSMutableString*) serialize: (NSArray*) array
	{
		NSMutableString* s = [NSMutableString string];
		for(id item in array) {
			[s appendString: [item serialize: @"RateAdvisement"]];
		}
		return s;
	}
@end
