/*
	RSPArrayOfAccessorial.h
	The implementation of properties and methods for the RSPArrayOfAccessorial array.
	Generated by SudzC.com
*/
#import "RSPArrayOfAccessorial.h"

#import "RSPAccessorial.h"
@implementation RSPArrayOfAccessorial

	+ (id) createWithNode: (CXMLNode*) node
	{
		return [[self alloc] initWithNode: node];
	}

	- (id) initWithNode: (CXMLNode*) node
	{
		if(self = [self init]) {
			for(CXMLElement* child in [node children])
			{
				RSPAccessorial* value = [[RSPAccessorial createWithNode: child] object];
				if(value != nil) {
					[self addObject: value];
				}
			}
		}
		return self;
	}
	
	+ (NSMutableString*) serialize: (NSArray*) array
	{
		NSMutableString* s = [NSMutableString string];
		for(id item in array) {
			[s appendString: [item serialize: @"Accessorial"]];
		}
		return s;
	}
@end
