/*
	RSPArrayOfFreight.h
	The interface definition of properties and methods for the RSPArrayOfFreight array.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class RSPFreight;
@interface RSPArrayOfFreight : SoapArray
{
}

@end
