/*
	RSPArrayOfString.h
	The interface definition of properties and methods for the RSPArrayOfString array.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@interface RSPArrayOfString : SoapArray
{
}

@end
