/*
	RSPBilling3rdParty.h
	The implementation of properties and methods for the RSPBilling3rdParty object.
	Generated by SudzC.com
*/
#import "RSPBilling3rdParty.h"

@implementation RSPBilling3rdParty
	@synthesize b3pBilltoHeader = _b3pBilltoHeader;
	@synthesize b3pName1 = _b3pName1;
	@synthesize b3pName2 = _b3pName2;
	@synthesize b3pName3 = _b3pName3;
	@synthesize b3pStreet1 = _b3pStreet1;
	@synthesize b3pStreet2 = _b3pStreet2;
	@synthesize b3pStreet3 = _b3pStreet3;
	@synthesize b3pStreet4 = _b3pStreet4;
	@synthesize b3pCity = _b3pCity;
	@synthesize b3pState = _b3pState;
	@synthesize b3pCountry = _b3pCountry;
	@synthesize b3pZip = _b3pZip;
	@synthesize b3pLatitude = _b3pLatitude;
	@synthesize b3pLongitude = _b3pLongitude;

	- (id) init
	{
		if(self = [super init])
		{
			self.b3pBilltoHeader = nil;
			self.b3pName1 = nil;
			self.b3pName2 = nil;
			self.b3pName3 = nil;
			self.b3pStreet1 = nil;
			self.b3pStreet2 = nil;
			self.b3pStreet3 = nil;
			self.b3pStreet4 = nil;
			self.b3pCity = nil;
			self.b3pState = nil;
			self.b3pCountry = nil;
			self.b3pZip = nil;
			self.b3pLatitude = nil;
			self.b3pLongitude = nil;

		}
		return self;
	}

	+ (RSPBilling3rdParty*) createWithNode: (CXMLNode*) node
	{
		if(node == nil) { return nil; }
		return [[self alloc] initWithNode: node];
	}

	- (id) initWithNode: (CXMLNode*) node {
		if(self = [super initWithNode: node])
		{
			self.b3pBilltoHeader = [Soap getNodeValue: node withName: @"b3pBilltoHeader"];
			self.b3pName1 = [Soap getNodeValue: node withName: @"b3pName1"];
			self.b3pName2 = [Soap getNodeValue: node withName: @"b3pName2"];
			self.b3pName3 = [Soap getNodeValue: node withName: @"b3pName3"];
			self.b3pStreet1 = [Soap getNodeValue: node withName: @"b3pStreet1"];
			self.b3pStreet2 = [Soap getNodeValue: node withName: @"b3pStreet2"];
			self.b3pStreet3 = [Soap getNodeValue: node withName: @"b3pStreet3"];
			self.b3pStreet4 = [Soap getNodeValue: node withName: @"b3pStreet4"];
			self.b3pCity = [Soap getNodeValue: node withName: @"b3pCity"];
			self.b3pState = [Soap getNodeValue: node withName: @"b3pState"];
			self.b3pCountry = [Soap getNodeValue: node withName: @"b3pCountry"];
			self.b3pZip = [Soap getNodeValue: node withName: @"b3pZip"];
			self.b3pLatitude = [Soap getNodeValue: node withName: @"b3pLatitude"];
			self.b3pLongitude = [Soap getNodeValue: node withName: @"b3pLongitude"];
		}
		return self;
	}

	- (NSMutableString*) serialize
	{
		return [self serialize: @"Billing3rdParty"];
	}
  
	- (NSMutableString*) serialize: (NSString*) nodeName
	{
		NSMutableString* s = [NSMutableString string];
		[s appendFormat: @"<%@", nodeName];
		[s appendString: [self serializeAttributes]];
		[s appendString: @">"];
		[s appendString: [self serializeElements]];
		[s appendFormat: @"</%@>", nodeName];
		return s;
	}
	
	- (NSMutableString*) serializeElements
	{
		NSMutableString* s = [super serializeElements];
		if (self.b3pBilltoHeader != nil) [s appendFormat: @"<b3pBilltoHeader>%@</b3pBilltoHeader>", [[self.b3pBilltoHeader stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];
		if (self.b3pName1 != nil) [s appendFormat: @"<b3pName1>%@</b3pName1>", [[self.b3pName1 stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];
		if (self.b3pName2 != nil) [s appendFormat: @"<b3pName2>%@</b3pName2>", [[self.b3pName2 stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];
		if (self.b3pName3 != nil) [s appendFormat: @"<b3pName3>%@</b3pName3>", [[self.b3pName3 stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];
		if (self.b3pStreet1 != nil) [s appendFormat: @"<b3pStreet1>%@</b3pStreet1>", [[self.b3pStreet1 stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];
		if (self.b3pStreet2 != nil) [s appendFormat: @"<b3pStreet2>%@</b3pStreet2>", [[self.b3pStreet2 stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];
		if (self.b3pStreet3 != nil) [s appendFormat: @"<b3pStreet3>%@</b3pStreet3>", [[self.b3pStreet3 stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];
		if (self.b3pStreet4 != nil) [s appendFormat: @"<b3pStreet4>%@</b3pStreet4>", [[self.b3pStreet4 stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];
		if (self.b3pCity != nil) [s appendFormat: @"<b3pCity>%@</b3pCity>", [[self.b3pCity stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];
		if (self.b3pState != nil) [s appendFormat: @"<b3pState>%@</b3pState>", [[self.b3pState stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];
		if (self.b3pCountry != nil) [s appendFormat: @"<b3pCountry>%@</b3pCountry>", [[self.b3pCountry stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];
		if (self.b3pZip != nil) [s appendFormat: @"<b3pZip>%@</b3pZip>", [[self.b3pZip stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];
		if (self.b3pLatitude != nil) [s appendFormat: @"<b3pLatitude>%@</b3pLatitude>", [[self.b3pLatitude stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];
		if (self.b3pLongitude != nil) [s appendFormat: @"<b3pLongitude>%@</b3pLongitude>", [[self.b3pLongitude stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];

		return s;
	}
	
	- (NSMutableString*) serializeAttributes
	{
		NSMutableString* s = [super serializeAttributes];

		return s;
	}
	
	-(BOOL)isEqual:(id)object{
		if(object != nil && [object isKindOfClass:[RSPBilling3rdParty class]]) {
			return [[self serialize] isEqualToString:[object serialize]];
		}
		return NO;
	}
	
	-(NSUInteger)hash{
		return [Soap generateHash:self];

	}

@end
