/*
	RSPCwtPricingDetails.h
	The interface definition of properties and methods for the RSPCwtPricingDetails object.
	Generated by SudzC.com
*/

#import "Soap.h"
	

@interface RSPCwtPricingDetails : SoapObject
{
	NSString* _cwtPieces;
	NSDecimalNumber* _cwtWeight;
	NSDecimalNumber* _cwtClass;
	NSDecimalNumber* _cwtCube;
	NSDecimalNumber* _cwtRatedClass;
	NSDecimalNumber* _cwtRate;
	
}
		
	@property (retain, nonatomic) NSString* cwtPieces;
	@property (retain, nonatomic) NSDecimalNumber* cwtWeight;
	@property (retain, nonatomic) NSDecimalNumber* cwtClass;
	@property (retain, nonatomic) NSDecimalNumber* cwtCube;
	@property (retain, nonatomic) NSDecimalNumber* cwtRatedClass;
	@property (retain, nonatomic) NSDecimalNumber* cwtRate;

	+ (RSPCwtPricingDetails*) createWithNode: (CXMLNode*) node;
	- (id) initWithNode: (CXMLNode*) node;
	- (NSMutableString*) serialize;
	- (NSMutableString*) serialize: (NSString*) nodeName;
	- (NSMutableString*) serializeAttributes;
	- (NSMutableString*) serializeElements;

@end
