/*
	RSPCwtPricingDetails.h
	The implementation of properties and methods for the RSPCwtPricingDetails object.
	Generated by SudzC.com
*/
#import "RSPCwtPricingDetails.h"

@implementation RSPCwtPricingDetails
	@synthesize cwtPieces = _cwtPieces;
	@synthesize cwtWeight = _cwtWeight;
	@synthesize cwtClass = _cwtClass;
	@synthesize cwtCube = _cwtCube;
	@synthesize cwtRatedClass = _cwtRatedClass;
	@synthesize cwtRate = _cwtRate;

	- (id) init
	{
		if(self = [super init])
		{
			self.cwtPieces = nil;
			self.cwtWeight = nil;
			self.cwtClass = nil;
			self.cwtCube = nil;
			self.cwtRatedClass = nil;
			self.cwtRate = nil;

		}
		return self;
	}

	+ (RSPCwtPricingDetails*) createWithNode: (CXMLNode*) node
	{
		if(node == nil) { return nil; }
		return [[self alloc] initWithNode: node];
	}

	- (id) initWithNode: (CXMLNode*) node {
		if(self = [super initWithNode: node])
		{
			self.cwtPieces = [Soap getNodeValue: node withName: @"cwtPieces"];
			self.cwtWeight = [NSDecimalNumber decimalNumberWithString: [Soap getNodeValue: node withName: @"cwtWeight"]];
			self.cwtClass = [NSDecimalNumber decimalNumberWithString: [Soap getNodeValue: node withName: @"cwtClass"]];
			self.cwtCube = [NSDecimalNumber decimalNumberWithString: [Soap getNodeValue: node withName: @"cwtCube"]];
			self.cwtRatedClass = [NSDecimalNumber decimalNumberWithString: [Soap getNodeValue: node withName: @"cwtRatedClass"]];
			self.cwtRate = [NSDecimalNumber decimalNumberWithString: [Soap getNodeValue: node withName: @"cwtRate"]];
		}
		return self;
	}

	- (NSMutableString*) serialize
	{
		return [self serialize: @"CwtPricingDetails"];
	}
  
	- (NSMutableString*) serialize: (NSString*) nodeName
	{
		NSMutableString* s = [NSMutableString string];
		[s appendFormat: @"<%@", nodeName];
		[s appendString: [self serializeAttributes]];
		[s appendString: @">"];
		[s appendString: [self serializeElements]];
		[s appendFormat: @"</%@>", nodeName];
		return s;
	}
	
	- (NSMutableString*) serializeElements
	{
		NSMutableString* s = [super serializeElements];
		if (self.cwtPieces != nil) [s appendFormat: @"<cwtPieces>%@</cwtPieces>", [[self.cwtPieces stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];
		if (self.cwtWeight != nil) [s appendFormat: @"<cwtWeight>%@</cwtWeight>", [NSString stringWithFormat: @"%@", self.cwtWeight]];
		if (self.cwtClass != nil) [s appendFormat: @"<cwtClass>%@</cwtClass>", [NSString stringWithFormat: @"%@", self.cwtClass]];
		if (self.cwtCube != nil) [s appendFormat: @"<cwtCube>%@</cwtCube>", [NSString stringWithFormat: @"%@", self.cwtCube]];
		if (self.cwtRatedClass != nil) [s appendFormat: @"<cwtRatedClass>%@</cwtRatedClass>", [NSString stringWithFormat: @"%@", self.cwtRatedClass]];
		if (self.cwtRate != nil) [s appendFormat: @"<cwtRate>%@</cwtRate>", [NSString stringWithFormat: @"%@", self.cwtRate]];

		return s;
	}
	
	- (NSMutableString*) serializeAttributes
	{
		NSMutableString* s = [super serializeAttributes];

		return s;
	}
	
	-(BOOL)isEqual:(id)object{
		if(object != nil && [object isKindOfClass:[RSPCwtPricingDetails class]]) {
			return [[self serialize] isEqualToString:[object serialize]];
		}
		return NO;
	}
	
	-(NSUInteger)hash{
		return [Soap generateHash:self];

	}

@end
