/*
	RSPDebugInfo.h
	The interface definition of properties and methods for the RSPDebugInfo object.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class RSPArrayOfString;

@interface RSPDebugInfo : SoapObject
{
	NSMutableArray* _info;
	
}
		
	@property (retain, nonatomic) NSMutableArray* info;

	+ (RSPDebugInfo*) createWithNode: (CXMLNode*) node;
	- (id) initWithNode: (CXMLNode*) node;
	- (NSMutableString*) serialize;
	- (NSMutableString*) serialize: (NSString*) nodeName;
	- (NSMutableString*) serializeAttributes;
	- (NSMutableString*) serializeElements;

@end
