/*
	RSPDebugInfo.h
	The implementation of properties and methods for the RSPDebugInfo object.
	Generated by SudzC.com
*/
#import "RSPDebugInfo.h"

#import "RSPArrayOfString.h"
@implementation RSPDebugInfo
	@synthesize info = _info;

	- (id) init
	{
		if(self = [super init])
		{
			self.info = [[NSMutableArray alloc] init];

		}
		return self;
	}

	+ (RSPDebugInfo*) createWithNode: (CXMLNode*) node
	{
		if(node == nil) { return nil; }
		return [[self alloc] initWithNode: node];
	}

	- (id) initWithNode: (CXMLNode*) node {
		if(self = [super initWithNode: node])
		{
			self.info = [[RSPArrayOfString createWithNode: [Soap getNode: node withName: @"info"]] object];
		}
		return self;
	}

	- (NSMutableString*) serialize
	{
		return [self serialize: @"DebugInfo"];
	}
  
	- (NSMutableString*) serialize: (NSString*) nodeName
	{
		NSMutableString* s = [NSMutableString string];
		[s appendFormat: @"<%@", nodeName];
		[s appendString: [self serializeAttributes]];
		[s appendString: @">"];
		[s appendString: [self serializeElements]];
		[s appendFormat: @"</%@>", nodeName];
		return s;
	}
	
	- (NSMutableString*) serializeElements
	{
		NSMutableString* s = [super serializeElements];
		if (self.info != nil && self.info.count > 0) {
			[s appendFormat: @"<info>%@</info>", [RSPArrayOfString serialize: self.info]];
		} else {
			[s appendString: @"<info/>"];
		}

		return s;
	}
	
	- (NSMutableString*) serializeAttributes
	{
		NSMutableString* s = [super serializeAttributes];

		return s;
	}
	
	-(BOOL)isEqual:(id)object{
		if(object != nil && [object isKindOfClass:[RSPDebugInfo class]]) {
			return [[self serialize] isEqualToString:[object serialize]];
		}
		return NO;
	}
	
	-(NSUInteger)hash{
		return [Soap generateHash:self];

	}

@end
