/*
	RSPEffectivePricing.h
	The implementation of properties and methods for the RSPEffectivePricing object.
	Generated by SudzC.com
*/
#import "RSPEffectivePricing.h"

@implementation RSPEffectivePricing
	@synthesize isMinimum = _isMinimum;
	@synthesize isPercentPricing = _isPercentPricing;
	@synthesize dollarOrPercentValue = _dollarOrPercentValue;

	- (id) init
	{
		if(self = [super init])
		{
			self.dollarOrPercentValue = nil;

		}
		return self;
	}

	+ (RSPEffectivePricing*) createWithNode: (CXMLNode*) node
	{
		if(node == nil) { return nil; }
		return [[self alloc] initWithNode: node];
	}

	- (id) initWithNode: (CXMLNode*) node {
		if(self = [super initWithNode: node])
		{
			self.isMinimum = [[Soap getNodeValue: node withName: @"isMinimum"] boolValue];
			self.isPercentPricing = [[Soap getNodeValue: node withName: @"isPercentPricing"] boolValue];
			self.dollarOrPercentValue = [NSDecimalNumber decimalNumberWithString: [Soap getNodeValue: node withName: @"dollarOrPercentValue"]];
		}
		return self;
	}

	- (NSMutableString*) serialize
	{
		return [self serialize: @"EffectivePricing"];
	}
  
	- (NSMutableString*) serialize: (NSString*) nodeName
	{
		NSMutableString* s = [NSMutableString string];
		[s appendFormat: @"<%@", nodeName];
		[s appendString: [self serializeAttributes]];
		[s appendString: @">"];
		[s appendString: [self serializeElements]];
		[s appendFormat: @"</%@>", nodeName];
		return s;
	}
	
	- (NSMutableString*) serializeElements
	{
		NSMutableString* s = [super serializeElements];
		[s appendFormat: @"<isMinimum>%@</isMinimum>", (self.isMinimum)?@"true":@"false"];
		[s appendFormat: @"<isPercentPricing>%@</isPercentPricing>", (self.isPercentPricing)?@"true":@"false"];
		if (self.dollarOrPercentValue != nil) [s appendFormat: @"<dollarOrPercentValue>%@</dollarOrPercentValue>", [NSString stringWithFormat: @"%@", self.dollarOrPercentValue]];

		return s;
	}
	
	- (NSMutableString*) serializeAttributes
	{
		NSMutableString* s = [super serializeAttributes];

		return s;
	}
	
	-(BOOL)isEqual:(id)object{
		if(object != nil && [object isKindOfClass:[RSPEffectivePricing class]]) {
			return [[self serialize] isEqualToString:[object serialize]];
		}
		return NO;
	}
	
	-(NSUInteger)hash{
		return [Soap generateHash:self];

	}

@end
