/*
	RSPEffectivePricing.h
	The interface definition of properties and methods for the RSPEffectivePricing object.
	Generated by SudzC.com
*/

#import "Soap.h"
	

@interface RSPEffectivePricing : SoapObject
{
	BOOL _isMinimum;
	BOOL _isPercentPricing;
	NSDecimalNumber* _dollarOrPercentValue;
	
}
		
	@property BOOL isMinimum;
	@property BOOL isPercentPricing;
	@property (retain, nonatomic) NSDecimalNumber* dollarOrPercentValue;

	+ (RSPEffectivePricing*) createWithNode: (CXMLNode*) node;
	- (id) initWithNode: (CXMLNode*) node;
	- (NSMutableString*) serialize;
	- (NSMutableString*) serialize: (NSString*) nodeName;
	- (NSMutableString*) serializeAttributes;
	- (NSMutableString*) serializeElements;

@end
