/*
	RSPFreightPricingDetails.h
	The interface definition of properties and methods for the RSPFreightPricingDetails object.
	Generated by SudzC.com
*/

#import "Soap.h"
	

@interface RSPFreightPricingDetails : SoapObject
{
	NSString* _description;
	NSDecimalNumber* _length;
	NSDecimalNumber* _width;
	NSDecimalNumber* _height;
	NSDecimalNumber* _freightClass;
	NSDecimalNumber* _weight;
	NSDecimalNumber* _ratedWeight;
	NSDecimalNumber* _volume;
	int _units;
	NSDecimalNumber* _cost;
	NSDecimalNumber* _charge;
	NSDecimalNumber* _costRate;
	NSDecimalNumber* _chargeRate;
	
}
		
	@property (retain, nonatomic) NSString* description;
	@property (retain, nonatomic) NSDecimalNumber* length;
	@property (retain, nonatomic) NSDecimalNumber* width;
	@property (retain, nonatomic) NSDecimalNumber* height;
	@property (retain, nonatomic) NSDecimalNumber* freightClass;
	@property (retain, nonatomic) NSDecimalNumber* weight;
	@property (retain, nonatomic) NSDecimalNumber* ratedWeight;
	@property (retain, nonatomic) NSDecimalNumber* volume;
	@property int units;
	@property (retain, nonatomic) NSDecimalNumber* cost;
	@property (retain, nonatomic) NSDecimalNumber* charge;
	@property (retain, nonatomic) NSDecimalNumber* costRate;
	@property (retain, nonatomic) NSDecimalNumber* chargeRate;

	+ (RSPFreightPricingDetails*) createWithNode: (CXMLNode*) node;
	- (id) initWithNode: (CXMLNode*) node;
	- (NSMutableString*) serialize;
	- (NSMutableString*) serialize: (NSString*) nodeName;
	- (NSMutableString*) serializeAttributes;
	- (NSMutableString*) serializeElements;

@end
