/*
	RSPPricingStrategyLevel.h
	The implementation of properties and methods for the RSPPricingStrategyLevel object.
	Generated by SudzC.com
*/
#import "RSPPricingStrategyLevel.h"

@implementation RSPPricingStrategyLevel
	@synthesize pricing_strategy_pk = _pricing_strategy_pk;
	@synthesize strategy_id = _strategy_id;

	- (id) init
	{
		if(self = [super init])
		{

		}
		return self;
	}

	+ (RSPPricingStrategyLevel*) createWithNode: (CXMLNode*) node
	{
		if(node == nil) { return nil; }
		return [[self alloc] initWithNode: node];
	}

	- (id) initWithNode: (CXMLNode*) node {
		if(self = [super initWithNode: node])
		{
			self.pricing_strategy_pk = [[Soap getNodeValue: node withName: @"pricing_strategy_pk"] intValue];
			self.strategy_id = [[Soap getNodeValue: node withName: @"strategy_id"] intValue];
		}
		return self;
	}

	- (NSMutableString*) serialize
	{
		return [self serialize: @"PricingStrategyLevel"];
	}
  
	- (NSMutableString*) serialize: (NSString*) nodeName
	{
		NSMutableString* s = [NSMutableString string];
		[s appendFormat: @"<%@", nodeName];
		[s appendString: [self serializeAttributes]];
		[s appendString: @">"];
		[s appendString: [self serializeElements]];
		[s appendFormat: @"</%@>", nodeName];
		return s;
	}
	
	- (NSMutableString*) serializeElements
	{
		NSMutableString* s = [super serializeElements];
		[s appendFormat: @"<pricing_strategy_pk>%@</pricing_strategy_pk>", [NSString stringWithFormat: @"%i", self.pricing_strategy_pk]];
		[s appendFormat: @"<strategy_id>%@</strategy_id>", [NSString stringWithFormat: @"%i", self.strategy_id]];

		return s;
	}
	
	- (NSMutableString*) serializeAttributes
	{
		NSMutableString* s = [super serializeAttributes];

		return s;
	}
	
	-(BOOL)isEqual:(id)object{
		if(object != nil && [object isKindOfClass:[RSPPricingStrategyLevel class]]) {
			return [[self serialize] isEqualToString:[object serialize]];
		}
		return NO;
	}
	
	-(NSUInteger)hash{
		return [Soap generateHash:self];

	}

@end
