/*
	RSPPalletPositions.h
	The interface definition of properties and methods for the RSPPalletPositions object.
	Generated by SudzC.com
*/

#import "Soap.h"
	

@interface RSPPalletPositions : SoapObject
{
	double _length;
	double _width;
	double _height;
	double _weight;
	int _positionCount;
	int _positionAdjustedCount;
	
}
		
	@property double length;
	@property double width;
	@property double height;
	@property double weight;
	@property int positionCount;
	@property int positionAdjustedCount;

	+ (RSPPalletPositions*) createWithNode: (CXMLNode*) node;
	- (id) initWithNode: (CXMLNode*) node;
	- (NSMutableString*) serialize;
	- (NSMutableString*) serialize: (NSString*) nodeName;
	- (NSMutableString*) serializeAttributes;
	- (NSMutableString*) serializeElements;

@end
