/*
	RSPPricingIncentive.h
	The interface definition of properties and methods for the RSPPricingIncentive object.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class RSPEffectivePricing;

@interface RSPPricingIncentive : SoapObject
{
	int _pricing_incentive_pk;
	int _cust_id;
	int _contract_id;
	BOOL _inbound;
	BOOL _outbound;
	BOOL _third_party;
	NSString* _mode;
	BOOL _active;
	NSDecimalNumber* _incentive_percent;
	NSDecimalNumber* _incentive_dollar;
	NSDecimalNumber* _min_percent;
	NSDecimalNumber* _min_dollar;
	NSDecimalNumber* _max_percent;
	NSDecimalNumber* _max_dollar;
	BOOL _incentive_percent_applies;
	BOOL _min_percent_applies;
	BOOL _max_percent_applies;
	BOOL _min_limit_enabled;
	BOOL _max_limit_enabled;
	int _org_id;
	NSString* _scac;
	RSPEffectivePricing* _effectivePricing;
	
}
		
	@property int pricing_incentive_pk;
	@property int cust_id;
	@property int contract_id;
	@property BOOL inbound;
	@property BOOL outbound;
	@property BOOL third_party;
	@property (retain, nonatomic) NSString* mode;
	@property BOOL active;
	@property (retain, nonatomic) NSDecimalNumber* incentive_percent;
	@property (retain, nonatomic) NSDecimalNumber* incentive_dollar;
	@property (retain, nonatomic) NSDecimalNumber* min_percent;
	@property (retain, nonatomic) NSDecimalNumber* min_dollar;
	@property (retain, nonatomic) NSDecimalNumber* max_percent;
	@property (retain, nonatomic) NSDecimalNumber* max_dollar;
	@property BOOL incentive_percent_applies;
	@property BOOL min_percent_applies;
	@property BOOL max_percent_applies;
	@property BOOL min_limit_enabled;
	@property BOOL max_limit_enabled;
	@property int org_id;
	@property (retain, nonatomic) NSString* scac;
	@property (retain, nonatomic) RSPEffectivePricing* effectivePricing;

	+ (RSPPricingIncentive*) createWithNode: (CXMLNode*) node;
	- (id) initWithNode: (CXMLNode*) node;
	- (NSMutableString*) serialize;
	- (NSMutableString*) serialize: (NSString*) nodeName;
	- (NSMutableString*) serializeAttributes;
	- (NSMutableString*) serializeElements;

@end
