/*
	RSPPricingTransactionCharge.h
	The interface definition of properties and methods for the RSPPricingTransactionCharge object.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class RSPEffectivePricing;

@interface RSPPricingTransactionCharge : SoapObject
{
	int _pricing_transaction_pk;
	int _cust_id;
	NSString* _mode;
	NSDecimalNumber* _charge_percent;
	NSDecimalNumber* _charge_dollar;
	NSDecimalNumber* _min_percent;
	NSDecimalNumber* _min_dollar;
	NSDecimalNumber* _max_percent;
	NSDecimalNumber* _max_dollar;
	BOOL _active;
	BOOL _charge_percent_applies;
	BOOL _min_percent_applies;
	BOOL _max_percent_applies;
	BOOL _min_limit_enabled;
	BOOL _max_limit_enabled;
	int _org_id;
	RSPEffectivePricing* _effectivePricing;
	
}
		
	@property int pricing_transaction_pk;
	@property int cust_id;
	@property (retain, nonatomic) NSString* mode;
	@property (retain, nonatomic) NSDecimalNumber* charge_percent;
	@property (retain, nonatomic) NSDecimalNumber* charge_dollar;
	@property (retain, nonatomic) NSDecimalNumber* min_percent;
	@property (retain, nonatomic) NSDecimalNumber* min_dollar;
	@property (retain, nonatomic) NSDecimalNumber* max_percent;
	@property (retain, nonatomic) NSDecimalNumber* max_dollar;
	@property BOOL active;
	@property BOOL charge_percent_applies;
	@property BOOL min_percent_applies;
	@property BOOL max_percent_applies;
	@property BOOL min_limit_enabled;
	@property BOOL max_limit_enabled;
	@property int org_id;
	@property (retain, nonatomic) RSPEffectivePricing* effectivePricing;

	+ (RSPPricingTransactionCharge*) createWithNode: (CXMLNode*) node;
	- (id) initWithNode: (CXMLNode*) node;
	- (NSMutableString*) serialize;
	- (NSMutableString*) serialize: (NSString*) nodeName;
	- (NSMutableString*) serializeAttributes;
	- (NSMutableString*) serializeElements;

@end
