/*
	RSPPricingContractLevel.h
	The interface definition of properties and methods for the RSPPricingContractLevel object.
	Generated by SudzC.com
*/

#import "Soap.h"
	
#import "RSPPricingBase.h"
@class RSPPricingBase;


@interface RSPPricingContractLevel : RSPPricingBase
{
	int _pricing_contract_pk;
	
}
		
	@property int pricing_contract_pk;

	+ (RSPPricingContractLevel*) createWithNode: (CXMLNode*) node;
	- (id) initWithNode: (CXMLNode*) node;
	- (NSMutableString*) serialize;
	- (NSMutableString*) serialize: (NSString*) nodeName;
	- (NSMutableString*) serializeAttributes;
	- (NSMutableString*) serializeElements;

@end
