/*
	RSPPricingAccessorial.h
	The interface definition of properties and methods for the RSPPricingAccessorial object.
	Generated by SudzC.com
*/

#import "Soap.h"
	

@interface RSPPricingAccessorial : SoapObject
{
	int _pricing_accessorial_pk;
	int _cust_id;
	NSString* _accessorial_code;
	NSDecimalNumber* _markup_percent;
	NSDecimalNumber* _markup_dollar;
	NSDecimalNumber* _min_percent;
	NSDecimalNumber* _min_dollar;
	NSDecimalNumber* _max_percent;
	NSDecimalNumber* _max_dollar;
	BOOL _markup_percent_applies;
	BOOL _min_percent_applies;
	BOOL _max_percent_applies;
	BOOL _min_limit_enabled;
	BOOL _max_limit_enabled;
	int _org_id;
	BOOL _active;
	BOOL _is_override;
	
}
		
	@property int pricing_accessorial_pk;
	@property int cust_id;
	@property (retain, nonatomic) NSString* accessorial_code;
	@property (retain, nonatomic) NSDecimalNumber* markup_percent;
	@property (retain, nonatomic) NSDecimalNumber* markup_dollar;
	@property (retain, nonatomic) NSDecimalNumber* min_percent;
	@property (retain, nonatomic) NSDecimalNumber* min_dollar;
	@property (retain, nonatomic) NSDecimalNumber* max_percent;
	@property (retain, nonatomic) NSDecimalNumber* max_dollar;
	@property BOOL markup_percent_applies;
	@property BOOL min_percent_applies;
	@property BOOL max_percent_applies;
	@property BOOL min_limit_enabled;
	@property BOOL max_limit_enabled;
	@property int org_id;
	@property BOOL active;
	@property BOOL is_override;

	+ (RSPPricingAccessorial*) createWithNode: (CXMLNode*) node;
	- (id) initWithNode: (CXMLNode*) node;
	- (NSMutableString*) serialize;
	- (NSMutableString*) serialize: (NSString*) nodeName;
	- (NSMutableString*) serializeAttributes;
	- (NSMutableString*) serializeElements;

@end
