/*
	RSPPalletPositions.h
	The implementation of properties and methods for the RSPPalletPositions object.
	Generated by SudzC.com
*/
#import "RSPPalletPositions.h"

@implementation RSPPalletPositions
	@synthesize length = _length;
	@synthesize width = _width;
	@synthesize height = _height;
	@synthesize weight = _weight;
	@synthesize positionCount = _positionCount;
	@synthesize positionAdjustedCount = _positionAdjustedCount;

	- (id) init
	{
		if(self = [super init])
		{

		}
		return self;
	}

	+ (RSPPalletPositions*) createWithNode: (CXMLNode*) node
	{
		if(node == nil) { return nil; }
		return [[self alloc] initWithNode: node];
	}

	- (id) initWithNode: (CXMLNode*) node {
		if(self = [super initWithNode: node])
		{
			self.length = [[Soap getNodeValue: node withName: @"length"] doubleValue];
			self.width = [[Soap getNodeValue: node withName: @"width"] doubleValue];
			self.height = [[Soap getNodeValue: node withName: @"height"] doubleValue];
			self.weight = [[Soap getNodeValue: node withName: @"weight"] doubleValue];
			self.positionCount = [[Soap getNodeValue: node withName: @"positionCount"] intValue];
			self.positionAdjustedCount = [[Soap getNodeValue: node withName: @"positionAdjustedCount"] intValue];
		}
		return self;
	}

	- (NSMutableString*) serialize
	{
		return [self serialize: @"PalletPositions"];
	}
  
	- (NSMutableString*) serialize: (NSString*) nodeName
	{
		NSMutableString* s = [NSMutableString string];
		[s appendFormat: @"<%@", nodeName];
		[s appendString: [self serializeAttributes]];
		[s appendString: @">"];
		[s appendString: [self serializeElements]];
		[s appendFormat: @"</%@>", nodeName];
		return s;
	}
	
	- (NSMutableString*) serializeElements
	{
		NSMutableString* s = [super serializeElements];
		[s appendFormat: @"<length>%@</length>", [NSString stringWithFormat: @"%f", self.length]];
		[s appendFormat: @"<width>%@</width>", [NSString stringWithFormat: @"%f", self.width]];
		[s appendFormat: @"<height>%@</height>", [NSString stringWithFormat: @"%f", self.height]];
		[s appendFormat: @"<weight>%@</weight>", [NSString stringWithFormat: @"%f", self.weight]];
		[s appendFormat: @"<positionCount>%@</positionCount>", [NSString stringWithFormat: @"%i", self.positionCount]];
		[s appendFormat: @"<positionAdjustedCount>%@</positionAdjustedCount>", [NSString stringWithFormat: @"%i", self.positionAdjustedCount]];

		return s;
	}
	
	- (NSMutableString*) serializeAttributes
	{
		NSMutableString* s = [super serializeAttributes];

		return s;
	}
	
	-(BOOL)isEqual:(id)object{
		if(object != nil && [object isKindOfClass:[RSPPalletPositions class]]) {
			return [[self serialize] isEqualToString:[object serialize]];
		}
		return NO;
	}
	
	-(NSUInteger)hash{
		return [Soap generateHash:self];

	}

@end
