/*
	RSPRateReturn.h
	The interface definition of properties and methods for the RSPRateReturn object.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class RSPArrayOfRateResponsePrivileged;
@class RSPRateError;
@class RSPArrayOfRateAdvisement;
@class RSPDebugInfo;

@interface RSPRateReturn : SoapObject
{
	NSMutableArray* _rrp;
	RSPRateError* _re;
	double _rateTiming;
	NSMutableArray* _ra;
	RSPDebugInfo* _di;
	NSString* _resRateReturnHeaderGuid;
	
}
		
	@property (retain, nonatomic) NSMutableArray* rrp;
	@property (retain, nonatomic) RSPRateError* re;
	@property double rateTiming;
	@property (retain, nonatomic) NSMutableArray* ra;
	@property (retain, nonatomic) RSPDebugInfo* di;
	@property (retain, nonatomic) NSString* resRateReturnHeaderGuid;

	+ (RSPRateReturn*) createWithNode: (CXMLNode*) node;
	- (id) initWithNode: (CXMLNode*) node;
	- (NSMutableString*) serialize;
	- (NSMutableString*) serialize: (NSString*) nodeName;
	- (NSMutableString*) serializeAttributes;
	- (NSMutableString*) serializeElements;

@end
