/*
	RSPRateReturn.h
	The implementation of properties and methods for the RSPRateReturn object.
	Generated by SudzC.com
*/
#import "RSPRateReturn.h"

#import "RSPArrayOfRateResponsePrivileged.h"
#import "RSPRateError.h"
#import "RSPArrayOfRateAdvisement.h"
#import "RSPDebugInfo.h"
@implementation RSPRateReturn
	@synthesize rrp = _rrp;
	@synthesize re = _re;
	@synthesize rateTiming = _rateTiming;
	@synthesize ra = _ra;
	@synthesize di = _di;
	@synthesize resRateReturnHeaderGuid = _resRateReturnHeaderGuid;

	- (id) init
	{
		if(self = [super init])
		{
			self.rrp = [[NSMutableArray alloc] init];
			self.re = nil; // [[RSPRateError alloc] init];
			self.ra = [[NSMutableArray alloc] init];
			self.di = nil; // [[RSPDebugInfo alloc] init];
			self.resRateReturnHeaderGuid = nil;

		}
		return self;
	}

	+ (RSPRateReturn*) createWithNode: (CXMLNode*) node
	{
		if(node == nil) { return nil; }
		return [[self alloc] initWithNode: node];
	}

	- (id) initWithNode: (CXMLNode*) node {
		if(self = [super initWithNode: node])
		{
			self.rrp = [[RSPArrayOfRateResponsePrivileged createWithNode: [Soap getNode: node withName: @"rrp"]] object];
			self.re = [[RSPRateError createWithNode: [Soap getNode: node withName: @"re"]] object];
			self.rateTiming = [[Soap getNodeValue: node withName: @"rateTiming"] doubleValue];
			self.ra = [[RSPArrayOfRateAdvisement createWithNode: [Soap getNode: node withName: @"ra"]] object];
			self.di = [[RSPDebugInfo createWithNode: [Soap getNode: node withName: @"di"]] object];
			self.resRateReturnHeaderGuid = [Soap getNodeValue: node withName: @"resRateReturnHeaderGuid"];
		}
		return self;
	}

	- (NSMutableString*) serialize
	{
		return [self serialize: @"RateReturn"];
	}
  
	- (NSMutableString*) serialize: (NSString*) nodeName
	{
		NSMutableString* s = [NSMutableString string];
		[s appendFormat: @"<%@", nodeName];
		[s appendString: [self serializeAttributes]];
		[s appendString: @">"];
		[s appendString: [self serializeElements]];
		[s appendFormat: @"</%@>", nodeName];
		return s;
	}
	
	- (NSMutableString*) serializeElements
	{
		NSMutableString* s = [super serializeElements];
		if (self.rrp != nil && self.rrp.count > 0) {
			[s appendFormat: @"<rrp>%@</rrp>", [RSPArrayOfRateResponsePrivileged serialize: self.rrp]];
		} else {
			[s appendString: @"<rrp/>"];
		}
		if (self.re != nil) [s appendString: [self.re serialize: @"re"]];
		[s appendFormat: @"<rateTiming>%@</rateTiming>", [NSString stringWithFormat: @"%f", self.rateTiming]];
		if (self.ra != nil && self.ra.count > 0) {
			[s appendFormat: @"<ra>%@</ra>", [RSPArrayOfRateAdvisement serialize: self.ra]];
		} else {
			[s appendString: @"<ra/>"];
		}
		if (self.di != nil) [s appendString: [self.di serialize: @"di"]];
		if (self.resRateReturnHeaderGuid != nil) [s appendFormat: @"<resRateReturnHeaderGuid>%@</resRateReturnHeaderGuid>", [[self.resRateReturnHeaderGuid stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];

		return s;
	}
	
	- (NSMutableString*) serializeAttributes
	{
		NSMutableString* s = [super serializeAttributes];

		return s;
	}
	
	-(BOOL)isEqual:(id)object{
		if(object != nil && [object isKindOfClass:[RSPRateReturn class]]) {
			return [[self serialize] isEqualToString:[object serialize]];
		}
		return NO;
	}
	
	-(NSUInteger)hash{
		return [Soap generateHash:self];

	}

@end
