/*
	RSPRateServicePrivileged.m
	The implementation classes and methods for the RateServicePrivileged web service.
	Generated by SudzC.com
*/

#import "RSPRateServicePrivileged.h"
				
#import "Soap.h"
	
#import "RSPStopOff.h"
#import "RSPFreight.h"
#import "RSPPalletPositions.h"
#import "RSPAccessorial.h"
#import "RSPAccessorialRateOverride.h"
#import "RSPArrayOfString.h"
#import "RSPPricingAccessorial.h"
#import "RSPPricingContractLevel.h"
#import "RSPEffectivePricing.h"
#import "RSPPricingStrategyLevel.h"
#import "RSPArrayOfDecimal.h"
#import "RSPCwtPricingDetails.h"
#import "RSPFreightPricingDetails.h"
#import "RSPRatedAccessorialPrivileged.h"
#import "RSPSupplement.h"
#import "RSPTerminalInfo.h"
#import "RSPBilling3rdParty.h"
#import "RSPRateError.h"
#import "RSPRateAdvisement.h"
#import "RSPArrayOfStopOff.h"
#import "RSPArrayOfFreight.h"
#import "RSPArrayOfPalletPositions.h"
#import "RSPArrayOfAccessorial.h"
#import "RSPArrayOfAccessorialRateOverride.h"
#import "RSPCarrierScacs.h"
#import "RSPArrayOfRateResponsePrivileged.h"
#import "RSPArrayOfPricingAccessorial.h"
#import "RSPPricingBase.h"
#import "RSPPricingTransactionCharge.h"
#import "RSPPricingIncentive.h"
#import "RSPArrayOfArrayOfDecimal.h"
#import "RSPArrayOfCwtPricingDetails.h"
#import "RSPArrayOfFreightPricingDetails.h"
#import "RSPArrayOfRatedAccessorialPrivileged.h"
#import "RSPArrayOfSupplement.h"
#import "RSPArrayOfTerminalInfo.h"
#import "RSPArrayOfRateAdvisement.h"
#import "RSPDebugInfo.h"
#import "RSPRateResponsePrivileged.h"
#import "RSPRateReturn.h"
#import "RSPRateRequestPrivileged.h"

/* Implementation of the service */
				
@implementation RSPRateServicePrivileged

	- (id) init
	{
		if(self = [super init])
		{
			self.serviceUrl = @"http://139.146.200.58/WebServicesPrivileged/RateServicePrivileged.asmx";
			self.namespace = @"http://eshipmanager.com/";
			self.headers = nil;
			self.logging = NO;
		}
		return self;
	}
	
	- (id) initWithUsername: (NSString*) username andPassword: (NSString*) password {
		if(self = [super initWithUsername:username andPassword:password]) {
		}
		return self;
	}
	
	+ (RSPRateServicePrivileged*) service {
		return [RSPRateServicePrivileged serviceWithUsername:nil andPassword:nil];
	}
	
	+ (RSPRateServicePrivileged*) serviceWithUsername: (NSString*) username andPassword: (NSString*) password {
		return [[RSPRateServicePrivileged alloc] initWithUsername:username andPassword:password];
	}

		
	// Returns NSString*
	/*  */
	- (SoapRequest*) TestDBConnection: (id <SoapDelegate>) handler
	{
		return [self TestDBConnection: handler action: nil];
	}

	- (SoapRequest*) TestDBConnection: (id) _target action: (SEL) _action
		{
		NSMutableArray* _params = [NSMutableArray array];
		
		NSString* _envelope = [Soap createEnvelope: @"TestDBConnection" forNamespace: self.namespace withParameters: _params withHeaders: self.headers];
		SoapRequest* _request = [SoapRequest create: _target action: _action service: self soapAction: @"http://eshipmanager.com/TestDBConnection" postData: _envelope deserializeTo: @"NSString"];
		[_request send];
		return _request;
	}

	// Returns NSString*
	/*  */
	- (SoapRequest*) TestRateCall: (id <SoapDelegate>) handler
	{
		return [self TestRateCall: handler action: nil];
	}

	- (SoapRequest*) TestRateCall: (id) _target action: (SEL) _action
		{
		NSMutableArray* _params = [NSMutableArray array];
		
		NSString* _envelope = [Soap createEnvelope: @"TestRateCall" forNamespace: self.namespace withParameters: _params withHeaders: self.headers];
		SoapRequest* _request = [SoapRequest create: _target action: _action service: self soapAction: @"http://eshipmanager.com/TestRateCall" postData: _envelope deserializeTo: @"NSString"];
		[_request send];
		return _request;
	}

	// Returns RSPRateReturn*
	/*  */
	- (SoapRequest*) RateShipment: (id <SoapDelegate>) handler rrp: (RSPRateRequestPrivileged*) rrp
	{
		return [self RateShipment: handler action: nil rrp: rrp];
	}

	- (SoapRequest*) RateShipment: (id) _target action: (SEL) _action rrp: (RSPRateRequestPrivileged*) rrp
		{
		NSMutableArray* _params = [NSMutableArray array];
		
		[_params addObject: [[SoapParameter alloc] initWithValue: rrp forName: @"rrp"]];
		NSString* _envelope = [Soap createEnvelope: @"RateShipment" forNamespace: self.namespace withParameters: _params withHeaders: self.headers];
		SoapRequest* _request = [SoapRequest create: _target action: _action service: self soapAction: @"http://eshipmanager.com/RateShipment" postData: _envelope deserializeTo: [RSPRateReturn alloc]];
		[_request send];
		return _request;
	}

    - (SoapRequest*) RateShipment: (id) _target action: (SEL) _action req: (QuoteRequest*) req
    {
        NSMutableArray* _params = [NSMutableArray array];

        // TO DO - Create RSPRateRequestPrivileged from QuoteRequest
        RSPRateRequestPrivileged* rrp = [[RSPRateRequestPrivileged alloc] init];
        
        [_params addObject: [[SoapParameter alloc] initWithValue: rrp forName: @"rrp"]];
        NSString* _envelope = [Soap createEnvelope: @"RateShipment" forNamespace: self.namespace withParameters: _params withHeaders: self.headers];
        SoapRequest* _request = [SoapRequest create: _target action: _action service: self soapAction: @"http://eshipmanager.com/RateShipment" postData: _envelope deserializeTo: [RSPRateReturn alloc]];
        [_request send];
        return _request;
    }

@end
	