/*
	RSPRateAdvisement.h
	The interface definition of properties and methods for the RSPRateAdvisement object.
	Generated by SudzC.com
*/

#import "Soap.h"
	

@interface RSPRateAdvisement : SoapObject
{
	NSString* _advisement;
	
}
		
	@property (retain, nonatomic) NSString* advisement;

	+ (RSPRateAdvisement*) createWithNode: (CXMLNode*) node;
	- (id) initWithNode: (CXMLNode*) node;
	- (NSMutableString*) serialize;
	- (NSMutableString*) serialize: (NSString*) nodeName;
	- (NSMutableString*) serializeAttributes;
	- (NSMutableString*) serializeElements;

@end
