/*
	RSPRateServicePrivileged.h
	The interface definition of classes and methods for the RateServicePrivileged web service.
	Generated by SudzC.com
*/
				
#import "Soap.h"
	
/* Add class references */
				
#import "RSPStopOff.h"
#import "RSPFreight.h"
#import "RSPPalletPositions.h"
#import "RSPAccessorial.h"
#import "RSPAccessorialRateOverride.h"
#import "RSPArrayOfString.h"
#import "RSPPricingAccessorial.h"
#import "RSPPricingContractLevel.h"
#import "RSPEffectivePricing.h"
#import "RSPPricingStrategyLevel.h"
#import "RSPArrayOfDecimal.h"
#import "RSPCwtPricingDetails.h"
#import "RSPFreightPricingDetails.h"
#import "RSPRatedAccessorialPrivileged.h"
#import "RSPSupplement.h"
#import "RSPTerminalInfo.h"
#import "RSPBilling3rdParty.h"
#import "RSPRateError.h"
#import "RSPRateAdvisement.h"
#import "RSPArrayOfStopOff.h"
#import "RSPArrayOfFreight.h"
#import "RSPArrayOfPalletPositions.h"
#import "RSPArrayOfAccessorial.h"
#import "RSPArrayOfAccessorialRateOverride.h"
#import "RSPCarrierScacs.h"
#import "RSPArrayOfRateResponsePrivileged.h"
#import "RSPArrayOfPricingAccessorial.h"
#import "RSPPricingBase.h"
#import "RSPPricingTransactionCharge.h"
#import "RSPPricingIncentive.h"
#import "RSPArrayOfArrayOfDecimal.h"
#import "RSPArrayOfCwtPricingDetails.h"
#import "RSPArrayOfFreightPricingDetails.h"
#import "RSPArrayOfRatedAccessorialPrivileged.h"
#import "RSPArrayOfSupplement.h"
#import "RSPArrayOfTerminalInfo.h"
#import "RSPArrayOfRateAdvisement.h"
#import "RSPDebugInfo.h"
#import "RSPRateResponsePrivileged.h"
#import "RSPRateReturn.h"
#import "RSPRateRequestPrivileged.h"

#import "QuoteRequest.h"


/* Interface for the service */
				
@interface RSPRateServicePrivileged : SoapService
		
	// Returns NSString*
	/*  */
	- (SoapRequest*) TestDBConnection: (id <SoapDelegate>) handler;
	- (SoapRequest*) TestDBConnection: (id) target action: (SEL) action;

	// Returns NSString*
	/*  */
	- (SoapRequest*) TestRateCall: (id <SoapDelegate>) handler;
	- (SoapRequest*) TestRateCall: (id) target action: (SEL) action;

	// Returns RSPRateReturn*
	/*  */
	- (SoapRequest*) RateShipment: (id <SoapDelegate>) handler rrp: (RSPRateRequestPrivileged*) rrp;
	- (SoapRequest*) RateShipment: (id) target action: (SEL) action rrp: (RSPRateRequestPrivileged*) rrp;
    - (SoapRequest*) RateShipment: (id) target action: (SEL) action req: (QuoteRequest* ) req;
		
	+ (RSPRateServicePrivileged*) service;
	+ (RSPRateServicePrivileged*) serviceWithUsername: (NSString*) username andPassword: (NSString*) password;
@end
	