/*
	RSPRateAdvisement.h
	The implementation of properties and methods for the RSPRateAdvisement object.
	Generated by SudzC.com
*/
#import "RSPRateAdvisement.h"

@implementation RSPRateAdvisement
	@synthesize advisement = _advisement;

	- (id) init
	{
		if(self = [super init])
		{
			self.advisement = nil;

		}
		return self;
	}

	+ (RSPRateAdvisement*) createWithNode: (CXMLNode*) node
	{
		if(node == nil) { return nil; }
		return [[self alloc] initWithNode: node];
	}

	- (id) initWithNode: (CXMLNode*) node {
		if(self = [super initWithNode: node])
		{
			self.advisement = [Soap getNodeValue: node withName: @"advisement"];
		}
		return self;
	}

	- (NSMutableString*) serialize
	{
		return [self serialize: @"RateAdvisement"];
	}
  
	- (NSMutableString*) serialize: (NSString*) nodeName
	{
		NSMutableString* s = [NSMutableString string];
		[s appendFormat: @"<%@", nodeName];
		[s appendString: [self serializeAttributes]];
		[s appendString: @">"];
		[s appendString: [self serializeElements]];
		[s appendFormat: @"</%@>", nodeName];
		return s;
	}
	
	- (NSMutableString*) serializeElements
	{
		NSMutableString* s = [super serializeElements];
		if (self.advisement != nil) [s appendFormat: @"<advisement>%@</advisement>", [[self.advisement stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];

		return s;
	}
	
	- (NSMutableString*) serializeAttributes
	{
		NSMutableString* s = [super serializeAttributes];

		return s;
	}
	
	-(BOOL)isEqual:(id)object{
		if(object != nil && [object isKindOfClass:[RSPRateAdvisement class]]) {
			return [[self serialize] isEqualToString:[object serialize]];
		}
		return NO;
	}
	
	-(NSUInteger)hash{
		return [Soap generateHash:self];

	}

@end
