/*
	RSPStopOff.h
	The implementation of properties and methods for the RSPStopOff object.
	Generated by SudzC.com
*/
#import "RSPStopOff.h"

@implementation RSPStopOff
	@synthesize city = _city;
	@synthesize state = _state;
	@synthesize country = _country;
	@synthesize zip = _zip;

	- (id) init
	{
		if(self = [super init])
		{
			self.city = nil;
			self.state = nil;
			self.country = nil;
			self.zip = nil;

		}
		return self;
	}

	+ (RSPStopOff*) createWithNode: (CXMLNode*) node
	{
		if(node == nil) { return nil; }
		return [[self alloc] initWithNode: node];
	}

	- (id) initWithNode: (CXMLNode*) node {
		if(self = [super initWithNode: node])
		{
			self.city = [Soap getNodeValue: node withName: @"city"];
			self.state = [Soap getNodeValue: node withName: @"state"];
			self.country = [Soap getNodeValue: node withName: @"country"];
			self.zip = [Soap getNodeValue: node withName: @"zip"];
		}
		return self;
	}

	- (NSMutableString*) serialize
	{
		return [self serialize: @"StopOff"];
	}
  
	- (NSMutableString*) serialize: (NSString*) nodeName
	{
		NSMutableString* s = [NSMutableString string];
		[s appendFormat: @"<%@", nodeName];
		[s appendString: [self serializeAttributes]];
		[s appendString: @">"];
		[s appendString: [self serializeElements]];
		[s appendFormat: @"</%@>", nodeName];
		return s;
	}
	
	- (NSMutableString*) serializeElements
	{
		NSMutableString* s = [super serializeElements];
		if (self.city != nil) [s appendFormat: @"<city>%@</city>", [[self.city stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];
		if (self.state != nil) [s appendFormat: @"<state>%@</state>", [[self.state stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];
		if (self.country != nil) [s appendFormat: @"<country>%@</country>", [[self.country stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];
		if (self.zip != nil) [s appendFormat: @"<zip>%@</zip>", [[self.zip stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];

		return s;
	}
	
	- (NSMutableString*) serializeAttributes
	{
		NSMutableString* s = [super serializeAttributes];

		return s;
	}
	
	-(BOOL)isEqual:(id)object{
		if(object != nil && [object isKindOfClass:[RSPStopOff class]]) {
			return [[self serialize] isEqualToString:[object serialize]];
		}
		return NO;
	}
	
	-(NSUInteger)hash{
		return [Soap generateHash:self];

	}

@end
