/*
	RSPSupplement.h
	The interface definition of properties and methods for the RSPSupplement object.
	Generated by SudzC.com
*/

#import "Soap.h"
	

@interface RSPSupplement : SoapObject
{
	NSString* _description;
	NSString* _code;
	NSDecimalNumber* _cost;
	NSDecimalNumber* _charge;
	
}
		
	@property (retain, nonatomic) NSString* description;
	@property (retain, nonatomic) NSString* code;
	@property (retain, nonatomic) NSDecimalNumber* cost;
	@property (retain, nonatomic) NSDecimalNumber* charge;

	+ (RSPSupplement*) createWithNode: (CXMLNode*) node;
	- (id) initWithNode: (CXMLNode*) node;
	- (NSMutableString*) serialize;
	- (NSMutableString*) serialize: (NSString*) nodeName;
	- (NSMutableString*) serializeAttributes;
	- (NSMutableString*) serializeElements;

@end
