/*
	RSPSupplement.h
	The implementation of properties and methods for the RSPSupplement object.
	Generated by SudzC.com
*/
#import "RSPSupplement.h"

@implementation RSPSupplement
	@synthesize description = _description;
	@synthesize code = _code;
	@synthesize cost = _cost;
	@synthesize charge = _charge;

	- (id) init
	{
		if(self = [super init])
		{
			self.description = nil;
			self.code = nil;
			self.cost = nil;
			self.charge = nil;

		}
		return self;
	}

	+ (RSPSupplement*) createWithNode: (CXMLNode*) node
	{
		if(node == nil) { return nil; }
		return [[self alloc] initWithNode: node];
	}

	- (id) initWithNode: (CXMLNode*) node {
		if(self = [super initWithNode: node])
		{
			self.description = [Soap getNodeValue: node withName: @"description"];
			self.code = [Soap getNodeValue: node withName: @"code"];
			self.cost = [NSDecimalNumber decimalNumberWithString: [Soap getNodeValue: node withName: @"cost"]];
			self.charge = [NSDecimalNumber decimalNumberWithString: [Soap getNodeValue: node withName: @"charge"]];
		}
		return self;
	}

	- (NSMutableString*) serialize
	{
		return [self serialize: @"Supplement"];
	}
  
	- (NSMutableString*) serialize: (NSString*) nodeName
	{
		NSMutableString* s = [NSMutableString string];
		[s appendFormat: @"<%@", nodeName];
		[s appendString: [self serializeAttributes]];
		[s appendString: @">"];
		[s appendString: [self serializeElements]];
		[s appendFormat: @"</%@>", nodeName];
		return s;
	}
	
	- (NSMutableString*) serializeElements
	{
		NSMutableString* s = [super serializeElements];
		if (self.description != nil) [s appendFormat: @"<description>%@</description>", [[self.description stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];
		if (self.code != nil) [s appendFormat: @"<code>%@</code>", [[self.code stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];
		if (self.cost != nil) [s appendFormat: @"<cost>%@</cost>", [NSString stringWithFormat: @"%@", self.cost]];
		if (self.charge != nil) [s appendFormat: @"<charge>%@</charge>", [NSString stringWithFormat: @"%@", self.charge]];

		return s;
	}
	
	- (NSMutableString*) serializeAttributes
	{
		NSMutableString* s = [super serializeAttributes];

		return s;
	}
	
	-(BOOL)isEqual:(id)object{
		if(object != nil && [object isKindOfClass:[RSPSupplement class]]) {
			return [[self serialize] isEqualToString:[object serialize]];
		}
		return NO;
	}
	
	-(NSUInteger)hash{
		return [Soap generateHash:self];

	}

@end
