/*
	RSPSudzc.m
	Creates a list of the services available with the RSP prefix.
	Generated by SudzC.com
*/
#import "RSPSudzc.h"

@implementation RSPSudzC

@synthesize logging, server, defaultServer;

@synthesize rateServicePrivileged;


#pragma mark Initialization

-(id)initWithServer:(NSString*)serverName{
	if(self = [self init]) {
		self.server = serverName;
	}
	return self;
}

+(RSPSudzC*)sudzc{
	return (RSPSudzC*)[[RSPSudzC alloc] init];
}

+(RSPSudzC*)sudzcWithServer:(NSString*)serverName{
	return (RSPSudzC*)[[RSPSudzC alloc] initWithServer:serverName];
}

#pragma mark Methods

-(void)setLogging:(BOOL)value{
	logging = value;
	[self updateServices];
}

-(void)setServer:(NSString*)value{
	server = value;
	[self updateServices];
}

-(void)updateServices{

	[self updateService: self.rateServicePrivileged];
}

-(void)updateService:(SoapService*)service{
	service.logging = self.logging;
	if(self.server == nil || self.server.length < 1) { return; }
	service.serviceUrl = [service.serviceUrl stringByReplacingOccurrencesOfString:defaultServer withString:self.server];
}

#pragma mark Getter Overrides


-(RSPRateServicePrivileged*)rateServicePrivileged{
	if(rateServicePrivileged == nil) {
		rateServicePrivileged = [[RSPRateServicePrivileged alloc] init];
	}
	return rateServicePrivileged;
}


@end
			