/*
	RSPSudzc.h
	Creates a list of the services available with the RSP prefix.
	Generated by SudzC.com
*/
#import "RSPRateServicePrivileged.h"

@interface RSPSudzC : NSObject {
	BOOL logging;
	NSString* server;
	NSString* defaultServer;
RSPRateServicePrivileged* rateServicePrivileged;

}

-(id)initWithServer:(NSString*)serverName;
-(void)updateService:(SoapService*)service;
-(void)updateServices;
+(RSPSudzC*)sudzc;
+(RSPSudzC*)sudzcWithServer:(NSString*)serverName;

@property (nonatomic) BOOL logging;
@property (nonatomic, retain) NSString* server;
@property (nonatomic, retain) NSString* defaultServer;

@property (nonatomic, retain, readonly) RSPRateServicePrivileged* rateServicePrivileged;

@end
			