/*
	RSPStopOff.h
	The interface definition of properties and methods for the RSPStopOff object.
	Generated by SudzC.com
*/

#import "Soap.h"
	

@interface RSPStopOff : SoapObject
{
	NSString* _city;
	NSString* _state;
	NSString* _country;
	NSString* _zip;
	
}
		
	@property (retain, nonatomic) NSString* city;
	@property (retain, nonatomic) NSString* state;
	@property (retain, nonatomic) NSString* country;
	@property (retain, nonatomic) NSString* zip;

	+ (RSPStopOff*) createWithNode: (CXMLNode*) node;
	- (id) initWithNode: (CXMLNode*) node;
	- (NSMutableString*) serialize;
	- (NSMutableString*) serialize: (NSString*) nodeName;
	- (NSMutableString*) serializeAttributes;
	- (NSMutableString*) serializeElements;

@end
