/*
	RSPTerminalInfo.h
	The interface definition of properties and methods for the RSPTerminalInfo object.
	Generated by SudzC.com
*/

#import "Soap.h"
	

@interface RSPTerminalInfo : SoapObject
{
	NSString* _termCity;
	NSString* _termCode;
	NSString* _termContact;
	NSString* _termContactTitle;
	NSString* _termEmail;
	NSString* _termFax;
	NSString* _termName;
	NSString* _termState;
	NSString* _termStreet1;
	NSString* _termStreet2;
	NSString* _termTel;
	NSString* _termTollFree;
	NSString* _termZip;
	
}
		
	@property (retain, nonatomic) NSString* termCity;
	@property (retain, nonatomic) NSString* termCode;
	@property (retain, nonatomic) NSString* termContact;
	@property (retain, nonatomic) NSString* termContactTitle;
	@property (retain, nonatomic) NSString* termEmail;
	@property (retain, nonatomic) NSString* termFax;
	@property (retain, nonatomic) NSString* termName;
	@property (retain, nonatomic) NSString* termState;
	@property (retain, nonatomic) NSString* termStreet1;
	@property (retain, nonatomic) NSString* termStreet2;
	@property (retain, nonatomic) NSString* termTel;
	@property (retain, nonatomic) NSString* termTollFree;
	@property (retain, nonatomic) NSString* termZip;

	+ (RSPTerminalInfo*) createWithNode: (CXMLNode*) node;
	- (id) initWithNode: (CXMLNode*) node;
	- (NSMutableString*) serialize;
	- (NSMutableString*) serialize: (NSString*) nodeName;
	- (NSMutableString*) serializeAttributes;
	- (NSMutableString*) serializeElements;

@end
