/*
	CFCArrayOf_xsd_anyType.h
	The interface definition of properties and methods for the CFCArrayOf_xsd_anyType object.
	Generated by SudzC.com
*/

#import "Soap.h"
	

@interface CFCArrayOf_xsd_anyType : SoapObject
{
	
}
		

	+ (CFCArrayOf_xsd_anyType*) createWithNode: (CXMLNode*) node;
	- (id) initWithNode: (CXMLNode*) node;
	- (NSMutableString*) serialize;
	- (NSMutableString*) serialize: (NSString*) nodeName;
	- (NSMutableString*) serializeAttributes;
	- (NSMutableString*) serializeElements;

@end
