/*
	CFCCFCInvocationException.h
	The interface definition of properties and methods for the CFCCFCInvocationException object.
	Generated by SudzC.com
*/

#import "Soap.h"
	

@interface CFCCFCInvocationException : SoapObject
{
	
}
		

	+ (CFCCFCInvocationException*) createWithNode: (CXMLNode*) node;
	- (id) initWithNode: (CXMLNode*) node;
	- (NSMutableString*) serialize;
	- (NSMutableString*) serialize: (NSString*) nodeName;
	- (NSMutableString*) serializeAttributes;
	- (NSMutableString*) serializeElements;

@end
