/*
	CFCmapItem.h
	The implementation of properties and methods for the CFCmapItem object.
	Generated by SudzC.com
*/
#import "CFCmapItem.h"

@implementation CFCmapItem
	@synthesize key = _key;
	@synthesize value = _value;

	- (id) init
	{
		if(self = [super init])
		{

		}
		return self;
	}

	+ (CFCmapItem*) createWithNode: (CXMLNode*) node
	{
		if(node == nil) { return nil; }
		return [[self alloc] initWithNode: node];
	}

	- (id) initWithNode: (CXMLNode*) node {
		if(self = [super initWithNode: node])
		{
			self.key = [Soap deserialize: [Soap getNode: node withName: @"key"]];
			self.value = [Soap deserialize: [Soap getNode: node withName: @"value"]];
		}
		return self;
	}

	- (NSMutableString*) serialize
	{
		return [self serialize: @"mapItem"];
	}
  
	- (NSMutableString*) serialize: (NSString*) nodeName
	{
		NSMutableString* s = [NSMutableString string];
		[s appendFormat: @"<%@", nodeName];
		[s appendString: [self serializeAttributes]];
		[s appendString: @">"];
		[s appendString: [self serializeElements]];
		[s appendFormat: @"</%@>", nodeName];
		return s;
	}
	
	- (NSMutableString*) serializeElements
	{
		NSMutableString* s = [super serializeElements];
		if (self.key != nil) [s appendString: [Soap serialize: self.key]];
		if (self.value != nil) [s appendString: [Soap serialize: self.value]];

		return s;
	}
	
	- (NSMutableString*) serializeAttributes
	{
		NSMutableString* s = [super serializeAttributes];

		return s;
	}
	
	-(BOOL)isEqual:(id)object{
		if(object != nil && [object isKindOfClass:[CFCmapItem class]]) {
			return [[self serialize] isEqualToString:[object serialize]];
		}
		return NO;
	}
	
	-(NSUInteger)hash{
		return [Soap generateHash:self];

	}

@end
