/*
	CFCMap.h
	The implementation of properties and methods for the CFCMap array.
	Generated by SudzC.com
*/
#import "CFCMap.h"

#import "CFCmapItem.h"
@implementation CFCMap

	+ (id) createWithNode: (CXMLNode*) node
	{
		return [[self alloc] initWithNode: node];
	}

	- (id) initWithNode: (CXMLNode*) node
	{
		if(self = [self init]) {
			for(CXMLElement* child in [node children])
			{
				CFCmapItem* value = [[CFCmapItem createWithNode: child] object];
				if(value != nil) {
					[self addObject: value];
				}
			}
		}
		return self;
	}
	
	+ (NSMutableString*) serialize: (NSArray*) array
	{
		NSMutableString* s = [NSMutableString string];
		for(id item in array) {
			[s appendString: [item serialize: @"mapItem"]];
		}
		return s;
	}
@end
