/*
	CFCPrintService.h
	The interface definition of classes and methods for the PrintService web service.
	Generated by SudzC.com
*/
				
#import "Soap.h"
	
/* Add class references */
				
#import "CFCArrayOf_xsd_anyType.h"
#import "CFCArrayOf_xsd_string.h"
#import "CFCArrayOfArrayOf_xsd_anyType.h"
#import "CFCCFCInvocationException.h"
#import "CFCMap.h"
#import "CFCmapItem.h"
#import "CFCQueryBean.h"

/* Interface for the service */
				
@interface CFCPrintService : SoapService
		
	// Returns NSMutableArray*
	/*  */
	- (SoapRequest*) PrintCarrierReturn: (id <SoapDelegate>) handler BolData: (NSMutableArray*) BolData CarrierData: (CFCArrayOf_xsd_anyType*) CarrierData;
	- (SoapRequest*) PrintCarrierReturn: (id) target action: (SEL) action BolData: (NSMutableArray*) BolData CarrierData: (CFCArrayOf_xsd_anyType*) CarrierData;

		
	+ (CFCPrintService*) service;
	+ (CFCPrintService*) serviceWithUsername: (NSString*) username andPassword: (NSString*) password;
@end
	