/*
	CFCPrintService.m
	The implementation classes and methods for the PrintService web service.
	Generated by SudzC.com
*/

#import "CFCPrintService.h"
				
#import "Soap.h"
	
#import "CFCArrayOf_xsd_anyType.h"
#import "CFCArrayOf_xsd_string.h"
#import "CFCArrayOfArrayOf_xsd_anyType.h"
#import "CFCCFCInvocationException.h"
#import "CFCMap.h"
#import "CFCmapItem.h"
#import "CFCQueryBean.h"

/* Implementation of the service */
				
@implementation CFCPrintService

	- (id) init
	{
		if(self = [super init])
		{
			self.serviceUrl = @"http://test1.eshipmanager.com/cfc/print.cfc";
			self.namespace = @"http://cfc";
			self.headers = nil;
			self.logging = NO;
		}
		return self;
	}
	
	- (id) initWithUsername: (NSString*) username andPassword: (NSString*) password {
		if(self = [super initWithUsername:username andPassword:password]) {
		}
		return self;
	}
	
	+ (CFCPrintService*) service {
		return [CFCPrintService serviceWithUsername:nil andPassword:nil];
	}
	
	+ (CFCPrintService*) serviceWithUsername: (NSString*) username andPassword: (NSString*) password {
		return [[CFCPrintService alloc] initWithUsername:username andPassword:password];
	}

		
	// Returns NSMutableArray*
	/*  */
	- (SoapRequest*) PrintCarrierReturn: (id <SoapDelegate>) handler BolData: (NSMutableArray*) BolData CarrierData: (CFCArrayOf_xsd_anyType*) CarrierData
	{
		return [self PrintCarrierReturn: handler action: nil BolData: BolData CarrierData: CarrierData];
	}

	- (SoapRequest*) PrintCarrierReturn: (id) _target action: (SEL) _action BolData: (NSMutableArray*) BolData CarrierData: (CFCArrayOf_xsd_anyType*) CarrierData
		{
		NSMutableArray* _params = [NSMutableArray array];
		
		[_params addObject: [[SoapParameter alloc] initWithValue: BolData forName: @"BolData"]];
		[_params addObject: [[SoapParameter alloc] initWithValue: CarrierData forName: @"CarrierData"]];
		NSString* _envelope = [Soap createEnvelope: @"PrintCarrierReturn" forNamespace: self.namespace withParameters: _params withHeaders: self.headers];
		SoapRequest* _request = [SoapRequest create: _target action: _action service: self soapAction: @"" postData: _envelope deserializeTo: [CFCmapItem alloc]];
		[_request send];
		return _request;
	}


@end
	