/*
	CFCQueryBean.h
	The interface definition of properties and methods for the CFCQueryBean object.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class CFCArrayOf_xsd_string;
@class CFCArrayOfArrayOf_xsd_anyType;

@interface CFCQueryBean : SoapObject
{
	CFCArrayOf_xsd_string* _columnList;
	CFCArrayOfArrayOf_xsd_anyType* _data;
	
}
		
	@property (retain, nonatomic) CFCArrayOf_xsd_string* columnList;
	@property (retain, nonatomic) CFCArrayOfArrayOf_xsd_anyType* data;

	+ (CFCQueryBean*) createWithNode: (CXMLNode*) node;
	- (id) initWithNode: (CXMLNode*) node;
	- (NSMutableString*) serialize;
	- (NSMutableString*) serialize: (NSString*) nodeName;
	- (NSMutableString*) serializeAttributes;
	- (NSMutableString*) serializeElements;

@end
