/*
	CFCQueryBean.h
	The implementation of properties and methods for the CFCQueryBean object.
	Generated by SudzC.com
*/
#import "CFCQueryBean.h"

#import "CFCArrayOf_xsd_string.h"
#import "CFCArrayOfArrayOf_xsd_anyType.h"
@implementation CFCQueryBean
	@synthesize columnList = _columnList;
	@synthesize data = _data;

	- (id) init
	{
		if(self = [super init])
		{
			self.columnList = nil; // [[CFCArrayOf_xsd_string alloc] init];
			self.data = nil; // [[CFCArrayOfArrayOf_xsd_anyType alloc] init];

		}
		return self;
	}

	+ (CFCQueryBean*) createWithNode: (CXMLNode*) node
	{
		if(node == nil) { return nil; }
		return [[self alloc] initWithNode: node];
	}

	- (id) initWithNode: (CXMLNode*) node {
		if(self = [super initWithNode: node])
		{
			self.columnList = [[CFCArrayOf_xsd_string createWithNode: [Soap getNode: node withName: @"columnList"]] object];
			self.data = [[CFCArrayOfArrayOf_xsd_anyType createWithNode: [Soap getNode: node withName: @"data"]] object];
		}
		return self;
	}

	- (NSMutableString*) serialize
	{
		return [self serialize: @"QueryBean"];
	}
  
	- (NSMutableString*) serialize: (NSString*) nodeName
	{
		NSMutableString* s = [NSMutableString string];
		[s appendFormat: @"<%@", nodeName];
		[s appendString: [self serializeAttributes]];
		[s appendString: @">"];
		[s appendString: [self serializeElements]];
		[s appendFormat: @"</%@>", nodeName];
		return s;
	}
	
	- (NSMutableString*) serializeElements
	{
		NSMutableString* s = [super serializeElements];
		if (self.columnList != nil) [s appendString: [self.columnList serialize: @"columnList"]];
		if (self.data != nil) [s appendString: [self.data serialize: @"data"]];

		return s;
	}
	
	- (NSMutableString*) serializeAttributes
	{
		NSMutableString* s = [super serializeAttributes];

		return s;
	}
	
	-(BOOL)isEqual:(id)object{
		if(object != nil && [object isKindOfClass:[CFCQueryBean class]]) {
			return [[self serialize] isEqualToString:[object serialize]];
		}
		return NO;
	}
	
	-(NSUInteger)hash{
		return [Soap generateHash:self];

	}

@end
