/*
	CFCSudzc.h
	Creates a list of the services available with the CFC prefix.
	Generated by SudzC.com
*/
#import "CFCPrintService.h"

@interface CFCSudzC : NSObject {
	BOOL logging;
	NSString* server;
	NSString* defaultServer;
CFCPrintService* printService;

}

-(id)initWithServer:(NSString*)serverName;
-(void)updateService:(SoapService*)service;
-(void)updateServices;
+(CFCSudzC*)sudzc;
+(CFCSudzC*)sudzcWithServer:(NSString*)serverName;

@property (nonatomic) BOOL logging;
@property (nonatomic, retain) NSString* server;
@property (nonatomic, retain) NSString* defaultServer;

@property (nonatomic, retain, readonly) CFCPrintService* printService;

@end
			