/*
	CFCSudzc.m
	Creates a list of the services available with the CFC prefix.
	Generated by SudzC.com
*/
#import "CFCSudzc.h"

@implementation CFCSudzC

@synthesize logging, server, defaultServer;

@synthesize printService;


#pragma mark Initialization

-(id)initWithServer:(NSString*)serverName{
	if(self = [self init]) {
		self.server = serverName;
	}
	return self;
}

+(CFCSudzC*)sudzc{
	return (CFCSudzC*)[[CFCSudzC alloc] init];
}

+(CFCSudzC*)sudzcWithServer:(NSString*)serverName{
	return (CFCSudzC*)[[CFCSudzC alloc] initWithServer:serverName];
}

#pragma mark Methods

-(void)setLogging:(BOOL)value{
	logging = value;
	[self updateServices];
}

-(void)setServer:(NSString*)value{
	server = value;
	[self updateServices];
}

-(void)updateServices{

	[self updateService: self.printService];
}

-(void)updateService:(SoapService*)service{
	service.logging = self.logging;
	if(self.server == nil || self.server.length < 1) { return; }
	service.serviceUrl = [service.serviceUrl stringByReplacingOccurrencesOfString:defaultServer withString:self.server];
}

#pragma mark Getter Overrides


-(CFCPrintService*)printService{
	if(printService == nil) {
		printService = [[CFCPrintService alloc] init];
	}
	return printService;
}


@end
			