/*
 Soap+Prefix.m
 Provides Soap methods with access to the custom prefix.
 Generated by SudzC.com
*/

#import "Soap.h"
#import "Soap+Prefixcfc.h"

@implementation Soap (Prefix)

+(NSString*)prefixCFC { return @"CFC"; }

@end
			